// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFokwLzSWP8JH9J4Typ3exHvj7W-plo_E',
    appId: '1:287754492166:web:83ceaa80278b3b5d3be687',
    messagingSenderId: '287754492166',
    projectId: 'sintaxismemorizer',
    authDomain: 'sintaxismemorizer.firebaseapp.com',
    storageBucket: 'sintaxismemorizer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1XBwpgAM5549aExe-BZaia1flHrZcZ0',
    appId: '1:287754492166:android:bf9f4898035298ee3be687',
    messagingSenderId: '287754492166',
    projectId: 'sintaxismemorizer',
    storageBucket: 'sintaxismemorizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4tIRap8fs04-7jIJ7P4cNSk9i9gAomhQ',
    appId: '1:287754492166:ios:308536bf75ad6c6b3be687',
    messagingSenderId: '287754492166',
    projectId: 'sintaxismemorizer',
    storageBucket: 'sintaxismemorizer.firebasestorage.app',
    androidClientId: '287754492166-piep6pj32bfkqeska2a1oerfguoh6h8m.apps.googleusercontent.com',
    iosClientId: '287754492166-23js3l57ib2759kno1nfarvtcsb0bdqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sintaxismemorizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4tIRap8fs04-7jIJ7P4cNSk9i9gAomhQ',
    appId: '1:287754492166:ios:308536bf75ad6c6b3be687',
    messagingSenderId: '287754492166',
    projectId: 'sintaxismemorizer',
    storageBucket: 'sintaxismemorizer.firebasestorage.app',
    androidClientId: '287754492166-piep6pj32bfkqeska2a1oerfguoh6h8m.apps.googleusercontent.com',
    iosClientId: '287754492166-23js3l57ib2759kno1nfarvtcsb0bdqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sintaxismemorizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFokwLzSWP8JH9J4Typ3exHvj7W-plo_E',
    appId: '1:287754492166:web:ebbc2ba70015c6383be687',
    messagingSenderId: '287754492166',
    projectId: 'sintaxismemorizer',
    authDomain: 'sintaxismemorizer.firebaseapp.com',
    storageBucket: 'sintaxismemorizer.firebasestorage.app',
  );

}